version: '3'

services:
  proxy_reverse:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    links:
        - sentry-base
    depends_on:
        - sentry-base
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - proxy.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c " exec nginx"
    