version: '3'


services:
  # OPTIONAL: If you want to get emails from sentry include this docker container
  sentry-base:
    image: 'sentry:latest'
    container_name: sentry-base
    restart: unless-stopped
    depends_on:
      - sentry-redis
      - sentry-postgres
    links:
      - sentry-redis
      - sentry-postgres
    ports:
      - 9000:9000
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files
#      - /srv/sentry/etc:/etc/sentry
# Uncomment the line above if using the GitHub plugin
  sentry-cron:
    image: 'sentry:latest'
    restart: unless-stopped
    depends_on:
      - sentry-base
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files
#      - /srv/sentry/etc:/etc/sentry
# Uncomment the line above if using the GitHub plugin
  sentry-worker:
    image: 'sentry:latest'
    depends_on:
      - sentry-base
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files
#      - /srv/sentry/etc:/etc/sentry
# Uncomment the line above if using the GitHub plugin
  sentry-redis:
    image: 'redis:latest'
  sentry-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry 
    volumes:
      - /srv/sentry/postgres:/var/lib/postgresql/data